import argparse
import torch
import numpy as np


# Map data types to PyTorch types
DTYPE_MAP = {
    "bf16": torch.bfloat16,
    "f32": torch.float32,
    "i8": torch.int8,
    "i16": torch.int16,
    "i32": torch.int32,
}

# Map data types to C++ types
CPP_DTYPE_MAP = {
    "bf16": "std::bfloat16_t",
    "f32": "float",
    "i8": "int8_t",
    "i16": "int16_t", 
    "i32": "int32_t",
}

def generate_random_data(heads, M, K, N, dtype_in, transposed_b: bool, seed=42, verbose: bool = False):
    """Generate random input matrices A and B."""
    torch.manual_seed(seed)
    np.random.seed(seed)
    
    torch_dtype_in = DTYPE_MAP[dtype_in]
    
    if dtype_in in ["bf16", "f32"]:
        # VJUNG: Random numbers should NOT be uniformly between 0 and 1, because that would make the matrix product AB always close to 1.
        A = torch.rand(heads, M, K, dtype=torch.float32) * 4
        B = torch.rand(heads, K, N, dtype=torch.float32) * 4
    else:
        # For integer types, use uniform distribution
        if dtype_in == "i8":
            A = torch.randint(-128, 127, (heads, M, K), dtype=torch_dtype_in)
            B = torch.randint(-128, 127, (heads, K, N), dtype=torch_dtype_in)
        elif dtype_in == "i16":
            A = torch.randint(-2**15, 2**15 - 1, (heads, M, K), dtype=torch_dtype_in)
            B = torch.randint(-2**15, 2**15 - 1, (heads, K, N), dtype=torch_dtype_in)
        else:
            A = torch.randint(-1000, 1000, (heads, M, K), dtype=torch_dtype_in)
            B = torch.randint(-1000, 1000, (heads, K, N), dtype=torch_dtype_in)
            
    if transposed_b:
        B = B.permute(0, 2, 1)

    return A, B

def compute_golden_reference(A, B, dtype_out, transposed_b: bool):
    """Compute the golden reference using PyTorch matmul."""
    torch_dtype_out = DTYPE_MAP[dtype_out]
    
    if transposed_b:
        B = B.permute(0, 2, 1)
    
    # Perform matrix multiplication
    C = torch.matmul(A.to(torch_dtype_out), B.to(torch_dtype_out))
    
    # Convert to output type if needed
    if C.dtype != torch_dtype_out:
        C = C.to(torch_dtype_out)
    
    return C

def export_to_header(A, B, C, heads, M, K, N, dtype_in, dtype_out, header_path, verbose: bool = False):
    """Export matrices to C++ header file."""
    cpp_dtype_in = CPP_DTYPE_MAP[dtype_in]
    cpp_dtype_out = CPP_DTYPE_MAP[dtype_out]
    
    with open(header_path, 'w') as f:
        f.write(f"""// Generated golden reference values for matrix multiplication
// Number of Heads: H={heads}
// Matrix dimensions: M={M}, K={K}, N={N}
// Input type: {dtype_in} ({cpp_dtype_in})
// Output type: {dtype_out} ({cpp_dtype_out})
// Generated by generate_golden_reference.py

#ifndef GOLDEN_REFERENCE_H
#define GOLDEN_REFERENCE_H

#include <array>
#include <cstdint>
#include <stdfloat>

namespace golden_reference {{

// Matrix dimensions
constexpr int HEADS = {heads};
constexpr int M = {M};
constexpr int K = {K};
constexpr int N = {N};

// Input tensor A ({heads}x{M}x{K})
constexpr std::array<{cpp_dtype_in}, {heads * M * K}> A = {{
""")
        
        # Write matrix A data
        A_flat = A.flatten().to(torch.float32).numpy() if dtype_in == "bf16" else A.flatten().numpy()
        for i, val in enumerate(A_flat):
            if dtype_in == "bf16":
                # For bfloat16, we need to be careful with the representation
                f.write(f"    {cpp_dtype_in}({float(val):.6f}f)")
            elif dtype_in == "f32":
                f.write(f"    {float(val):.6f}f")
            else:
                f.write(f"    {int(val)}")
            
            if i < len(A_flat) - 1:
                f.write(",")
            if (i + 1) % 8 == 0:
                f.write("\n")
        
        f.write(f"""
}};

// Input tensor B ({heads}x{K}x{N})
constexpr std::array<{cpp_dtype_in}, {heads * K * N}> B = {{
""")
        
        # Write matrix B data
        B_flat = B.flatten().to(torch.float32).numpy() if dtype_in == "bf16" else B.flatten().numpy()
        for i, val in enumerate(B_flat):
            if dtype_in == "bf16":
                f.write(f"    {cpp_dtype_in}({float(val):.6f}f)")
            elif dtype_in == "f32":
                f.write(f"    {float(val):.6f}f")
            else:
                f.write(f"    {int(val)}")
            
            if i < len(B_flat) - 1:
                f.write(",")
            if (i + 1) % 8 == 0:
                f.write("\n")
        
        f.write(f"""
}};

// Golden reference output C ({heads}x{M}x{N})
constexpr std::array<{cpp_dtype_out}, {heads * M * N}> C_golden = {{
""")
        
        # Write matrix C data
        C_flat = C.flatten().to(torch.float32).numpy() if dtype_out == "bf16" else C.flatten().numpy()
        for i, val in enumerate(C_flat):
            if dtype_out == "bf16":
                f.write(f"    {cpp_dtype_out}({float(val):.6f}f)")
            elif dtype_out == "f32":
                f.write(f"    {float(val):.6f}f")
            else:
                f.write(f"    {int(val)}")
            
            if i < len(C_flat) - 1:
                f.write(",")
            if (i + 1) % 8 == 0:
                f.write("\n")
        
        f.write(f"""
}};

}} // namespace golden_reference

#endif // GOLDEN_REFERENCE_H
""")

def main():
    parser = argparse.ArgumentParser(description="Generate PyTorch golden reference for matrix multiplication")
    parser.add_argument("--heads", type=int, default=1, help="Number of heads")
    parser.add_argument("-M", type=int, default=256, help="Matrix dimension M")
    parser.add_argument("-K", type=int, default=256, help="Matrix dimension K")
    parser.add_argument("-N", type=int, default=256, help="Matrix dimension N")
    parser.add_argument("--dtype_in", type=str, choices=["bf16", "f32", "i8", "i16", "i32"], 
                       default="bf16", help="Input data type")
    parser.add_argument("--dtype_out", type=str, choices=["bf16", "f32", "i8", "i16", "i32"], 
                       default="bf16", help="Output data type")
    parser.add_argument("--transposed_b", type=int, 
                        help="Transpose matrix B before multiplication")
    parser.add_argument("--output", type=str, default="golden_reference.h", 
                       help="Output header file path")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    
    args = parser.parse_args()
    
    if args.verbose:
        print(f"Generating golden reference for {args.M}x{args.K}x{args.N} matrix multiplication with {args.heads} heads")
        print(f"Input type: {args.dtype_in}, Output type: {args.dtype_out}")
    
    # Generate random input matrices
    A, B = generate_random_data(args.heads, args.M, args.K, args.N, args.dtype_in, args.transposed_b, args.seed, args.verbose)
    
    if args.verbose:
        print("Generated input matrices A and B")
    
    # Compute golden reference
    C = compute_golden_reference(A, B, args.dtype_out, args.transposed_b)
    
    if args.verbose:
        print("Computed golden reference using PyTorch")
        print(f"A shape: {A.shape}, B shape: {B.shape}, C shape: {C.shape}")
    
    # Export to header file
    export_to_header(A, B, C, args.heads, args.M, args.K, args.N, args.dtype_in, args.dtype_out, args.output, args.verbose)
    
    if args.verbose:
        print(f"Exported golden reference to {args.output}")
    
    # Print some statistics
    if args.verbose:
        print(f"Tensor multiplication {args.heads}x{args.M}x{args.K} @ {args.K}x{args.N} = {args.heads}x{args.M}x{args.N}")
        print(f"Input type: {args.dtype_in}, Output type: {args.dtype_out}")
        print(f"A range: [{float(A.min()):.3f}, {float(A.max()):.3f}]")
        print(f"B range: [{float(B.min()):.3f}, {float(B.max()):.3f}]")
        print(f"C range: [{float(C.min()):.3f}, {float(C.max()):.3f}]")
        print(f"Golden reference exported to: {args.output}")

if __name__ == "__main__":
    main()
